vim.cmd("syntax iskeyword @,48-57,192-255,$,_,'")
vim.cmd("syntax keyword Keyword end taking give back giving print split into at is let be totally with over isn't cast rock roll or break")
vim.cmd("syntax keyword Conditional if else")
vim.cmd("syntax keyword Repeat while for of")
vim.cmd("syntax match Function /[^ ]* takes/")
--vim.cmd("syntax region String start=+\"+ end=+\"+ end=+/\\n+")
vim.cmd("hi Say guifg=Blue")
vim.cmd("syntax keyword Say says")
vim.cmd("syntax region String start=/says/ end=/\\n/ contains=Say")
vim.cmd("syntax keyword Boolean true false")
vim.cmd("syntax match Number /[0-9]/")
vim.cmd("syntax region Comment start=+(+ start=+\\[+ start=+{+ end=+)+ end=+]+ end=+}+")
vim.cmd("syntax match Operator /+/")
vim.cmd("syntax match Operator /-/")
vim.cmd("syntax match Operator /*/")
vim.cmd("syntax match Operator +/+")
vim.cmd("syntax match Operator +<+")
vim.cmd("syntax match Operator +>+")
vim.cmd("syntax match Operator +<=+")
vim.cmd("syntax match Operator +>=+")
vim.cmd("syntax match Delimiter +,+")
vim.cmd("syntax match Delimiter +\\.+")
